### ISSUE TITLE
Develop an android project with tauri 2.0, use rust-tun to create a virtual network card, and report an error InvalidConfig

### ISSUE THREAD

**Issue by xiongmao-f** [meh/rust-tun#105]
The specific error information is as follows. Do you need any special operations to develop on Android? Does anyone know how to write it? Can you give me guidance?
```
12-10 11:01:37.532  5863  5892 I RustStdoutStderr: thread '<unnamed>' panicked at src\commands.rs:148:30:
12-10 11:01:37.542  5863  5892 I RustStdoutStderr: Failed to tun_test: InvalidConfig
12-10 11:01:37.543  5863  5892 I RustStdoutStderr: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
12-10 11:01:37.558  5863  5892 I RustStdoutStderr: [2024-12-10T11:01:37Z TRACE jni::wrapper::strings::java_str] calling unchecked jni method: ReleaseStringUTFChars
12-10 11:01:37.559  5863  5892 I RustStdoutStderr: [2024-12-10T11:01:37Z TRACE jni::wrapper::strings::java_str] looking up jni method ReleaseStringUTFChars
12-10 11:01:37.571  5863  5892 I RustStdoutStderr: [2024-12-10T11:01:37Z TRACE jni::wrapper::strings::java_str] found jni method     
12-10 11:01:37.571  5863  5892 I RustStdoutStderr: [2024-12-10T11:01:37Z TRACE jni::wrapper::strings::java_str] calling unchecked jni method: ReleaseStringUTFChars
12-10 11:01:37.572  5863  5892 I RustStdoutStderr: [2024-12-10T11:01:37Z TRACE jni::wrapper::strings::java_str] looking up jni method ReleaseStringUTFChars
12-10 11:01:37.576  5863  5892 I RustStdoutStderr: [2024-12-10T11:01:37Z TRACE jni::wrapper::strings::java_str] found jni method
12-10 11:01:37.582  5863  5892 I RustStdoutStderr: thread '<unnamed>' panicked at library/core/src/panicking.rs:221:5:
12-10 11:01:37.588  5863  5892 I RustStdoutStderr: panic in a function that cannot unwind
12-10 11:01:37.589  5863  5892 I RustStdoutStderr: stack backtrace:
12-10 11:01:37.589  5863  5892 I RustStdoutStderr:    0:     0x74ad3904b7c5 - <unknown>
12-10 11:01:37.589  5863  5892 I RustStdoutStderr:    1:     0x74ad3906711b - <unknown>
12-10 11:01:37.589  5863  5892 I RustStdoutStderr:    2:     0x74ad3904782f - <unknown>
12-10 11:01:37.589  5863  5892 I RustStdoutStderr:    3:     0x74ad3904cb91 - <unknown>
12-10 11:01:37.589  5863  5892 I RustStdoutStderr:    4:     0x74ad3904c7ce - <unknown>
12-10 11:01:37.590  5863  5892 I RustStdoutStderr:    5:     0x74ad3904d6c8 - <unknown>
12-10 11:01:37.601  5863  5892 I RustStdoutStderr:    6:     0x74ad3904d523 - <unknown>
12-10 11:01:37.606  5863  5892 I RustStdoutStderr:    7:     0x74ad3904bc99 - <unknown>
12-10 11:01:37.606  5863  5892 I RustStdoutStderr:    8:     0x74ad3904d1e4 - <unknown>
12-10 11:01:37.606  5863  5892 I RustStdoutStderr:    9:     0x74ad39064575 - <unknown>
12-10 11:01:37.607  5863  5892 I RustStdoutStderr:   10:     0x74ad39064602 - <unknown>
12-10 11:01:37.643  5863  5892 I RustStdoutStderr:   11:     0x74ad39064826 - <unknown>
12-10 11:01:37.649  5863  5892 I RustStdoutStderr:   12:     0x74ad3834619c - <unknown>
12-10 11:01:37.663  5863  5892 I RustStdoutStderr: s_glBindAttribLocation: bind attrib 0 name _uposition
12-10 11:01:37.663  5863  5892 I RustStdoutStderr: s_glBindAttribLocation: bind attrib 1 name _ulocalCoord
12-10 11:01:37.726  5863  5892 I RustStdoutStderr:   13:     0x74adbf22b5ec - <unknown>
12-10 11:01:37.727  5863  5892 I RustStdoutStderr:   14:     0x74adbf212155 - <unknown>
12-10 11:01:37.728  5863  5892 I RustStdoutStderr:   15:     0x74adbf474bf6 - <unknown>
12-10 11:01:37.728  5863  5892 I RustStdoutStderr:   16:     0x74adbf5f9574 - <unknown>
12-10 11:01:37.729  5863  5892 I RustStdoutStderr:   17:     0x74adbf233102 - <unknown>
12-10 11:01:37.729  5863  5892 I RustStdoutStderr:   18:     0x74adbf22d2e6 - <unknown>
12-10 11:01:37.730  5863  5892 I RustStdoutStderr:   19:     0x74adbf5f206a - <unknown>
12-10 11:01:37.730  5863  5892 I RustStdoutStderr:   20:     0x74adbf9880ef - <unknown>
12-10 11:01:37.731  5863  5892 I RustStdoutStderr:   21:     0x74adbf22b77d - <unknown>
12-10 11:01:37.731  5863  5892 I RustStdoutStderr:   22:     0x74adbf212155 - <unknown>
12-10 11:01:37.731  5863  5892 I RustStdoutStderr:   23:     0x74adbf474bf6 - <unknown>
12-10 11:01:37.731  5863  5892 I RustStdoutStderr:   24:     0x74adbf875cf9 - <unknown>
12-10 11:01:37.731  5863  5892 I RustStdoutStderr:   25:     0x74adbf7056a3 - <unknown>
12-10 11:01:37.731  5863  5892 I RustStdoutStderr:   26:     0x74adbf67297c - <unknown>
12-10 11:01:37.737  5863  5892 I RustStdoutStderr:   27:     0x74adbf660e5f - <unknown>
12-10 11:01:37.738  5863  5892 I RustStdoutStderr: thread caused non-unwinding panic. aborting.
12-10 11:01:37.842  5863  5892 I RustStdoutStderr: s_glBindAttribLocation: bind attrib 0 name _uposition
12-10 11:01:37.842  5863  5892 I RustStdoutStderr: s_glBindAttribLocation: bind attrib 1 name _ucolor
12-10 11:01:37.842  5863  5892 I RustStdoutStderr: s_glBindAttribLocation: bind attrib 2 name _ulocalCoord
12-10 11:01:38.097  5863  5863 I ImeTracker: com.tauri_android_learn.app:c1b09a62: onRequestHide at ORIGIN_CLIENT reason HIDE_SOFT_INPUT_ON_ANIMATION_STATE_CHANGED fromUser false
12-10 11:01:38.101  5863  5863 I ImeTracker: com.tauri_android_learn.app:b57662a3: onHidden
--------- beginning of crash
12-10 11:01:39.551  5863  5940 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 5940 (JavaBridge), pid 5863 (droid_learn.app)
```

**Comment by xiongmao-f** [comment]
> Here is some sample code, hope it can help you.
> 
> https://github.com/tun2proxy/tun2proxy/blob/3fb02f0fc7d2e058d7b0660f068ed58df81cbc1b/src/mobile_api.rs#L30-L56

Thank you very much. I read these lines of code. There are several parameters needed in mobile_run. How can I get them?

**Comment by ssrlive** [comment]
https://github.com/tun2proxy/tun2proxy/wiki/Integrate-to-Android-platform

**Comment by xiongmao-f** [comment]
> https://github.com/tun2proxy/tun2proxy/wiki/Integrate-to-Android-platform

Okay, thank you
